apiVersion: v2
name: hello-node-api
description: A Helm chart for deploying the hello-node-api Node application
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/MathewsThankachan/hello-node-api.git
sources:
	- https://github.com/MathewsThankachan/hello-node-api.git
